### ISSUE TITLE
Reloading on error

### ISSUE THREAD

**Issue by nonybright** [MarkoMilos/Paginate#15]
Thanks a lot for this great library.I would like to reload to get contents in case there is an error in connection during trial.How possible is that?

**Comment by MarkoMilos** [comment]
@nonybright Hi, retrying your network request or database load is not up to this library. This library handles setup listview/recyclerview/loading row and tracking scroll events. If your data load fails you need to handle "retry case" yourself.
Use `hasMoreDataToLoad()` method to help you along the way.

**Comment by nonybright** [comment]
thnax a lot. Already did that

**Comment by MarkoMilos** [comment]
@nonybright ok closing this then.
