### ISSUE TITLE
unbind issue

### ISSUE THREAD

**Issue by xm-repo** [MarkoMilos/Paginate#19]
Hello! Thx for great library!

I found one strange feature, looks like error; when we make unbind, we take original adapter and cast it to BaseAdapter, but in case when it was custom adapter with different type and additional features, we discount it's type and features. I think we should get adapter type via reflection or generic type and return adapter with proper type as it was before. Thx!

@Override
    public void unbind() {
        // Swap back original scroll listener
        absListView.setOnScrollListener(scrollListener.getDelegateScrollListener());

```
    // Swap back source adapter
    if (absListView.getAdapter() instanceof WrapperAdapter) {
        WrapperAdapter wrapperAdapter = (WrapperAdapter) absListView.getAdapter();
        BaseAdapter adapter = (BaseAdapter !!!!! we should somehow get real adapter type here (via reflection, or generic type, otherwise we can loose type features)) wrapperAdapter.getWrappedAdapter();
        adapter.unregisterDataSetObserver(dataSetObserver);
        ((AdapterView) absListView).setAdapter(adapter);
    }
}
```

**Comment by MarkoMilos** [comment]
Hi @xm-repo,

can you explain a bit how can you lose features... after casting it is still the same object as before - your original source adapter. The only thing that `unbind()` does is to swap `WrapperAdapter` inserted by the lib with the original adapter that was set on `ListView` and it was temporary saved in `WrapperAdapter`.
We don't change the object itself along the way in any form.

So if you have some `SpecialAdapter` that extends `BaseAdapter`

- on bind - the instance of that adapter will be stored in `WrapperAdapter` and `WrapperAdapter` will be set on `ListView`
- after `unbind()` - the stored instance of `SpecialAdapter` will be set back on `ListView

**Comment by daimonkor** [comment]
@MarkoMilos I see some interesting state, reseting scroll positon after unbing, please fix, thanks.

**Comment by krazykira** [comment]
+1 i am also losing scroll position when i do unbind

**Comment by MarkoMilos** [comment]
This has been resolved as a part of the latest release (check out release 1.0.0)

I'm closing this MR, feel free to reopen if you still experiencing this issue.
