### ISSUE TITLE
pagination with different LayoutManager (CarouselLayoutManager)

### ISSUE THREAD

**Issue by himangipatel** [MarkoMilos/Paginate#26]
Hello,
I am using CarouselLayoutManager for my recycle view. I used your library for paginaion.

Its working fine with  linear, grid and staggered LayoutManager.
But I need to do pagination on CarouselLayoutManager. As I apply pagination  to CarouselLayoutManager its give following exception : 

 **java.lang.IllegalStateException: LayoutManager needs to subclass LinearLayoutManager or StaggeredGridLayoutManager  at com.paginate.recycler.RecyclerPaginate.checkEndOffset(RecyclerPaginate.java:91)  at com.paginate.recycler.RecyclerPaginate.<init>(RecyclerPaginate.java:50) at com.paginate.recycler.RecyclerPaginate$Builder.build(RecyclerPaginate.java:241)**

Thanks

**Comment by MarkoMilos** [comment]
As exception says this library is meant to be used with standard (Android built-in) layout managers. 
It does not support custom layout managers from 3rd party libraries like `CarouselLayoutManager `.
