### ISSUE TITLE
Does this library require any proguard configurations?

### ISSUE THREAD

**Issue by boomesh** [MarkoMilos/Paginate#29]
Perhaps update the readme with a Proguard FAQ or something

**Comment by j2emanue** [comment]
did you have any proguard issues  ?

**Comment by NoNews** [comment]
there is no reflection, not necessary in proguard

**Comment by MarkoMilos** [comment]
The library does not use any reflection, only the Android standard API.
Also only dependency of the library is `androidx.recyclerview:recyclerview:{version}`.

That said, no special proguard rules are required.
