### ISSUE TITLE
Nested Scroll view Paginate request

### ISSUE THREAD

**Issue by alihabbash** [MarkoMilos/Paginate#38]
Is there is any way to add support for nested scroll view as well 
So, the code will be 
`Paginate.with(nestedScrollView);`
as well as:
`Paginate.with(recyclerView);`

**Comment by MarkoMilos** [comment]
This is a duplicate of #22

**Comment by mohammedelnady** [comment]
Pagination repeated more and more with nestedscrollview

**Comment by ShineThyuZan** [comment]
how can i solve pagination and nestedscrollview error?
