### ISSUE TITLE
RecyclerView with GridLInearLayout manager Weird Behavior

### ISSUE THREAD

**Issue by ashraful29** [MarkoMilos/Paginate#5]
Sometime The RecyclerView Item Take Whole row og GridLayoutManger On load more Action I upload below image for understanding the problem. 
![sometimeadaptermismatch](https://cloud.githubusercontent.com/assets/6369083/13244801/4d293a96-da33-11e5-9168-aa0b23a95768.JPG)

**Comment by MarkoMilos** [comment]
Hi,

can you provide code snippet for Paginate setuping and how do you add more items into the list.
Can you confirm that this item (that takes full span) is the last item on a certain page?

**Comment by ashraful29** [comment]
There is  Paginate Initialization code.. Where newSpanCount is number of Grid Column
```
 int threshold=4;
        paginate = Paginate.with(listProduct, this)
                .setLoadingTriggerThreshold(threshold)
                .setLoadingListItemSpanSizeLookup(new LoadingListItemSpanLookup() {
                    @Override
                    public int getSpanSize() {
                        return newSpanCount ;
                    }
                })
                .build();
```
And below code is adding more items...
```
 int range = productAdapter.getItemCount();
            // productAdapter.products.addAll(productsResponse.getProducts());
            productAdapter.addAll(productsResponse.getProducts());
            loading = false;
            System.out.print("Size" + productList.size());
            productAdapter.notifyItemRangeInserted(range,productsResponse.getProducts().size());
            productAdapter.notifyDataSetChanged();
```

And The item which take full span is the first item in a particular page when loading more..

**Comment by MarkoMilos** [comment]
What's the implementation of `productAdapter.addAll(items)` -  do you call any adapter related callbacks inside that method? 

Why do you call both `notifyItemRangeInserted(int positionStart, itemCount)` and `notifyDataSetChanged()` ? 

Check the sample for the example for RecyclerView + GridLayoutManager with span = 2.

**Comment by MarkoMilos** [comment]
Since long inactivity on this issue, I will close it for now. Feel free to reopen it if you still have problems with this.
