### ISSUE TITLE
ReAttach the pagination

### ISSUE THREAD

**Issue by Mansourali** [MarkoMilos/Paginate#6]
Hi Marko
In may case I tried to reattach the pagination after I filter the items in the adapter, so i dont need the pagination since the items are static and depend on the items already exist.
after that, when the user click say all the item the pagination should reattach again.
How to do that.
Thanks for you help

**Comment by MarkoMilos** [comment]
@Mansourali You will need to use `unbind()` call in order to detach from pagination. Later on, once when user leaves "filter feature" you can setup pagination again as you want (just like the initial setup).

**Comment by MarkoMilos** [comment]
I will close this issue since there isn't any further actions regarding this.
