### ISSUE TITLE
plzzz help load more at start called two times 

### ISSUE THREAD

**Issue by kashifandroiddev** [MarkoMilos/Paginate#8]
` public void onLoadMore() {
        Log.d("p", "onLoadMore()");
            reqExp();
            loading = true;

    }`

`@Override
    public boolean isLoading() {
        Log.d("p", "isLoading()");
        return loading;
    }`

in my response from network 

` mUserLst = UserParse.Data(mResponse);
                        mAdopter.add(mUserLst);
                        loading = false;`

my problem is that when activity start on load more called two times. i dont understand
` Paginate.with(mRv,this)
                .setLoadingTriggerThreshold(2)
                .addLoadingListItem(true)
                .setLoadingListItemCreator(new CustomLoadingListItemCreator())
                .build();`

**Comment by MarkoMilos** [comment]
@kashifandroiddev can you assert that the value in `isLoading()` call is false both times ?

**Comment by kashifandroiddev** [comment]
i dell the project because your reply is very late .....

do me a favoour 
send ma code template that in working well.....

thanks
