### ISSUE TITLE
Loading list item show/hide

### ISSUE THREAD

**Issue by linkact** [MarkoMilos/Paginate#9]
Thank you for the library.

Is there any available method to forcely close(invisible) the loading list item when cannot get data from server... (for example.. when the server down)

**Comment by MarkoMilos** [comment]
@linkact have you tried with `setHasMoreDataToLoad(boolean)` call in a case where there is no connection. Right now there is no other explicit way to do this.

**Comment by planetwebsolution** [comment]
I do this after request finished with no record for hide loading view mPaginate.setHasMoreDataToLoad(true);
but its not working, I don't know why ?

**Comment by blank-space** [comment]
@planetwebsolution    you should  use **setHasMoreDataToLoad(false);**

**Comment by MarkoMilos** [comment]
As blank-space suggested you should use `setHasMoreDataToLoad(false);`

Closing this, please reopen if you still have an issue with this.
